name: dcldavid
favicon: null
layout_spectrum: 0.5328066861256957
typography_spectrum: 0.1378474379889667
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1075bd'
    - '#20407d'
    - '#70a2c0'
    - '#afcfe5'
  brandStrength: 0.5625
  lightness: 0.2769719164352864
  saturation: 0.1448958378750831
  rhythmicContrast: 0.5097198483999819
purpose: []
